<?php
$config = \Suggestotron\Config::get('site');
?>

<!doctype html>
<html>
    <head>
        <title><?=$config['title'];?></title>
		 <script src="//code.jquery.com/jquery-1.10.2.js"></script>
        <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
        <script type="text/javascript" src="/js/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>

<style>
/* Gradient color1 - color2 - color1 */ 
hr.style-one {
	border: 0; 
	height: 1px;
	background: #333;
	background-image: -webkit-linear-gradient(left, #ccc, #333, #ccc);
	background-image: -moz-linear-gradient(left, #ccc, #333, #ccc);
	background-image: -ms-linear-gradient(left, #ccc, #333, #ccc); 
	background-image: -o-linear-gradient(left, #ccc, #333, #ccc); 
	}
</style>
		
<script type="text/javascript">
    $(document).ready(function() {  
	
		$(function() {
				$("#divmessage").delay(1000).fadeOut(1000);
				
		});			

	});

</script> 
</head>
    <body>

	
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                    <div class="navbar-header">
                              <a class="navbar-brand" href="/">Test Suggestotron</a>
                    </div>
                    <form class="navbar-form navbar-right" role="search">
                            <a href="/add" class="btn btn-default">
                                    <span class="glyphicon glyphicon-plus-sign"></span>
                                        Add Topic
                            </a>
                    </form>
                  </div>
        </nav>

		<?php
		if (isset($_SESSION['success'])) {
			if ($_SESSION['success'] == 'yes') {
			// sa se afiseze mesaj de succes
			echo '<div class="alert alert-info" role="alert" id="divmessage">';
			echo 'Topic salvat / adaugat.';
			echo '</div>';		
			
			unset($_SESSION['success']);
			}
		}
		?>

		<?php 
		if (isset($_SESSION['comment'])) {
			if ($_SESSION['comment'] == 'yes') {
			echo '<div class="alert alert-info" role="alert" id="divmessage">';
			echo 'Comment saved.';
			echo '</div>';
			
			unset($_SESSION['comment']);
			}
		}
		?>

        <div class="container">
            <!-- Specific Page Content Goes Here -->
            <?php $this->content(); ?>
        </div>
        <script type="text/javascript">
            $('[data-toggle="popover"]').popover();
        </script>
		
					
						
	
    </body>
</html>