<h3>About Bombardier</h3>

<p>As the world’s only manufacturer of planes and trains, we’ve built
an extensive and diverse portfolio of winning mobility solutions.
Everywhere people travel by land and in the air, a Bombardier product is ready to transport them. 
From category-defining business jets and commercial aircraft designed for the challenges of today,
to sleek high speed trains and public transit that’s smarter than ever.</p>

<p>But it’s not just our products and services that make us a global leader. The most important
success factor is our employees, all 76,400 of them. 
Together we’re focused on making mobility more efficient, sustainable
and inviting than ever before. We call it The Evolution of Mobility.</p>

<p>Bombardier is headquartered in Montréal, Canada, traded on the Toronto Stock
Exchange (BBD) and listed on the Dow Jones Sustainability World and North America Indices. 
In the fiscal year ended December 31, 2013, we posted revenues of $18.2 billion USD.</p>

 
<h3>About Aerospace</h3>

<p>With more than 37,700 employees and a leadership position in global markets, Bombardier
Aerospace designs, manufactures and supports innovative aviation
products for the business, commercial, specialized and amphibious aircraft markets.
We have the most comprehensive aircraft portfolio and we hold the number
one position in business and regional aircraft. Our high-performance aircraft and 
services set the standard of excellence in several markets, including:</p>

    <ul>
	<li>Business aircraft - Learjet, Challenger and Global aircraft families</li>
    <li>Commercial aircraft - new CSeries program, CRJ Series and Q-Series aircraft families</li>
    <li>Amphibious aircraft - Bombardier 415 and Bombardier 415 MP aircraft</li>
    <li>Specialized aircraft solutions - Bombardier aircraft modified for special missions</li>
    <li>Aircraft services and training - aircraft parts, maintenance, comprehensive training, technical support and publications, and online services </li>
	</ul>