<?php

$topics = $this->topics;

function showTree2($data, $level,$topic_id) {    

		foreach ($data as $item) {  
		
			if ($item['id_comment'] == 0) {
				$id = $item['id'];
				$id_comment = $item['id_comment'];
				$author =  $item['author'];
				$content =  $item['content'];
				
			} else if ($item['id_comment'] != 0  ) {
				$id = $item['id'];
				$id_comment = $item['id_comment'];
				$author =  str_repeat(' - ', $level) . $item['author'];   
				$content =  $item['content'];   
			} else {
				$id = $item['id'];
				$id_comment = $item['id_comment'];
				$author = str_repeat(' - ', $level). $item['author'];
				$content = str_repeat(' - ', $level). $item['content'];
			}

			global $result;

			$result[] = array(
				'row1' 	=> '<div id=reply_'.$id.$id_comment.'>',
				'row2'	=> $author . ' reply: ' . $content . '',
				'row3'	=> '<button type="button" id="comments_' . $id.$id_comment. '" class="btn btn-default btn-xs pull-right"><span class="glyphicon glyphicon-comment" class="show_hide"></span> Add reply</button>',
				'row4'	=> '<input type = "hidden" id="comments_comments_'.$id.$id_comment.'" name="id_comment_'.$id_comment.'" value='.$id_comment.'>',
				'row5'	=> '<input type = "hidden" id="parent_comments_'.$id.$id_comment.'" name="id_parent_'.$id.'" value='.$id.'>',
				'row6'	=> '<input type = "hidden" id="topic_comments_'.$id.$id_comment.'" name="id_topic'.$topic_id.'" value='.$topic_id.'>',
				'row7'	=> '</div>',
				'row8'	=>  $id.$id_comment,
			);
			
			if (isset($item['children'])) {                    
				showTree2($item['children'], $level + 1, $topic_id );
			} 
		
        }
	return $result;        
}

foreach ($topics as $topic) {
    ?>
    <section class="bg-warning">
		<!-- <form class="navbar-form" role="search" > -->
		
        <div class="row">
            <div class="col-xs-12">
                <h3><?=$topic['title'];?></h3>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-8">
                <p class="text-muted">
                    <?=nl2br($topic['description']);?>
                </p>
            </div>
            <div class="col-xs-4">
			
				<?php include('votes_form.phtml')?>
			
            </div>
        </div>

		<!---   add comments  --->
		<div>
			<button type="button" id="form_<?php echo $topic['id']; ?>" class="btn btn-default btn-s"><span class="glyphicon glyphicon-comment" class="show_hide"></span> Add comment</button>
			</br></br>

			<div id="comment_form_<?php echo $topic['id']; ?>" style="width:500px">
			</div>

		</div>	
		<!---   add comments  --->
		
		

		<!---   show comments  --->
		
		<?php if(count($topic['comments']) != 0) { ?>
		
			<fieldset class="alert alert-success" style="width:800px" >
			<legend style="margin-bottom:10px; font-size:16px;">Comments</legend>

			<?php $results = showTree2($topic['comments'], $level =0, $topic['id']);
			
			foreach ($results as $rezultat) {
				echo $rezultat['row1']. '</br>';
				echo $rezultat['row2'];
				echo $rezultat['row3'];
				echo $rezultat['row4'];
				echo $rezultat['row5'];
				echo $rezultat['row6'];
				echo $rezultat['row7'];
				
				?>	<div id="form_comments_<?php echo $rezultat['row8']; ?>" style="width:500px"></div>
			
			<?php
			}
			unset($GLOBALS['result']);
			?>
			</fieldset>
			
		
		<?php } ?>

		<!---   show comments  --->		


    </section>
    <hr>
	
    <?php } ?>

<form class="navbar-form navbar-right" role="search">
	<a href="/about" class="btn btn-default"><span class="glyphicon glyphicon-info-sign"></span> About</a>
</form>


<!---  comments --->
<script type="text/javascript">
$("[id^='form_']").on("click", function() {
	// alert(this.id);
	if ($("#myForm_"+this.id).length === 0){

		var elem = document.getElementById("comment_"+this.id);
		
			my_form=document.createElement('FORM');
			my_form.name='myForm_'+this.id;
			my_form.id='myForm_'+this.id;
			my_form.method='POST';
			my_form.action='/addCommenttoDB';

			my_tb=document.createElement('INPUT');
			my_tb.setAttribute("class", "form-control");
			my_tb.setAttribute("width", "200px");
			my_tb.type='TEXT';
			my_tb.name='name';

			var namelabel = document.createElement('label'); // Create Label for Name Field
			namelabel.setAttribute("class","col-sm-2 control-label");
			namelabel.innerHTML = "Name : "; // Set Field Labels

			my_form.appendChild(namelabel);
			my_form.appendChild(my_tb);

			var linebreak = document.createElement('br');
			my_form.appendChild(linebreak);


			var namelabel2 = document.createElement('label'); // Create Label for Name Field
			namelabel2.setAttribute("class","col-sm-2 control-label");
			namelabel2.innerHTML = "Comment: "; // Set Field Labels

			my_tb2=document.createElement('textarea');;
			my_tb2.setAttribute("name", "comment");
			my_tb2.setAttribute("rows", "3");
			my_tb2.setAttribute("cols", "60");

			my_form.appendChild(namelabel2);
			my_form.appendChild(my_tb2);
			
			
			my_tb3=document.createElement('INPUT');
			my_tb3.setAttribute("type", "hidden");
			my_tb3.name = 'id_parrent';
			my_tb3.value = 0;			
			
			my_tb4=document.createElement('INPUT');
			my_tb4.setAttribute("type", "hidden");
			my_tb4.name = 'id_comment';
			my_tb4.value = 0;			
			
			my_tb5=document.createElement('INPUT');
			my_tb5.setAttribute("type", "hidden");
			my_tb5.name = 'id_topic';
			my_tb5.value = (this.id).substr(5);
			
			my_tb6=document.createElement('INPUT');
			my_tb6.setAttribute("type", "hidden");
			my_tb6.name = 'date';
			my_tb6.value = '<?php echo $today = date("Y-m-d");?>';

			my_form.appendChild(my_tb3);
			my_form.appendChild(my_tb4);
			my_form.appendChild(my_tb5);
			my_form.appendChild(my_tb6);
			
			var submitelement = document.createElement('input'); // Append Submit Button
			submitelement.setAttribute("type", "submit");
			submitelement.setAttribute("name", "submit");
			submitelement.setAttribute("value", "Send");
			submitelement.setAttribute("class", "btn btn-default btn-s");
			my_form.appendChild(submitelement);

			document.getElementById("comment_"+this.id).appendChild(my_form);

	} else {
		$("#comment_"+this.id).slideToggle();
	};

	
});
</script>

<script type="text/javascript">
$("[id^='comments_']").on("click", function() {

	// alert(this.id);
	
	if ($("#myForm_"+this.id).length === 0){

		var elem = document.getElementById("form_"+this.id);
		
			my_form=document.createElement('FORM');
			my_form.name='myForm_'+this.id;
			my_form.id='myForm_'+this.id;
			my_form.method='POST';
			my_form.action='/addCommenttoDB';

			my_tb=document.createElement('INPUT');
			my_tb.setAttribute("class", "form-control");
			my_tb.setAttribute("width", "200px");
			my_tb.type='TEXT';
			my_tb.name='name';

			var namelabel = document.createElement('label'); // Create Label for Name Field
			namelabel.setAttribute("class","col-sm-2 control-label");
			namelabel.innerHTML = "Name : "; // Set Field Labels

			my_form.appendChild(namelabel);
			my_form.appendChild(my_tb);

			var linebreak = document.createElement('br');
			my_form.appendChild(linebreak);


			var namelabel2 = document.createElement('label'); // Create Label for Name Field
			namelabel2.setAttribute("class","col-sm-2 control-label");
			namelabel2.innerHTML = "Comment: "; // Set Field Labels

			my_tb2=document.createElement('textarea');;
			my_tb2.setAttribute("name", "comment");
			my_tb2.setAttribute("rows", "3");
			my_tb2.setAttribute("cols", "60");

			my_form.appendChild(namelabel2);
			my_form.appendChild(my_tb2);

			my_tb3=document.createElement('INPUT');
			my_tb3.setAttribute("type", "hidden");
			my_tb3.name = 'id_parrent';
			my_tb3.value = document.getElementById('comments_'+this.id).value;
			
			my_tb4=document.createElement('INPUT');
			my_tb4.setAttribute("type", "hidden");
			my_tb4.name = 'id_comment';
			my_tb4.value = document.getElementById('parent_'+this.id).value;

			my_tb5=document.createElement('INPUT');
			my_tb5.setAttribute("type", "hidden");
			my_tb5.name = 'id_topic';
			my_tb5.value = document.getElementById('topic_'+this.id).value;

			my_tb6=document.createElement('INPUT');
			my_tb6.setAttribute("type", "hidden");
			my_tb6.name = 'date';
			my_tb6.value = '<?php echo $today = date("Y-m-d");?>';
			
			my_form.appendChild(my_tb3);
			my_form.appendChild(my_tb4);
			my_form.appendChild(my_tb5);
			my_form.appendChild(my_tb6);
			
			document.getElementById('comments_'+this.id).value
			
			var submitelement = document.createElement('input'); // Append Submit Button
			submitelement.setAttribute("type", "submit");
			submitelement.setAttribute("name", "submit");
			submitelement.setAttribute("value", "Send");
			submitelement.setAttribute("class", "btn btn-default btn-s");
			my_form.appendChild(submitelement);

			document.getElementById("form_"+this.id).appendChild(my_form);
			
	// alert(document.getElementById('comments_'+this.id).value);
	} else {
		$("#form_"+this.id).slideToggle();
	};

	
});


</script>


	