<?php

$topics = $this->topics;

function showTree2($data, $level,$topic_id) {    

		foreach ($data as $item) {  
		
				$id = $item['id'];
				$id_comment = $item['id_comment'];
				$author =  str_repeat(' - ', $level) . $item['author'];   
				$content =  $item['content'];   

			echo '<div id=reply_'.$id.$id_comment.'></br>';
			echo $author . ' reply: ' . $content . '';
			echo '<button type="button" id="comments_' . $id.$id_comment. '" class="btn btn-default btn-xs pull-right"><span class="glyphicon glyphicon-comment" class="show_hide"></span> Add reply</button>';
			echo '<input type = "hidden" id="comments_comments_'.$id.$id_comment.'" name="id_comment_'.$id_comment.'" value='.$id_comment.'>';
			echo '<input type = "hidden" id="parent_comments_'.$id.$id_comment.'" name="id_parent_'.$id.'" value='.$id.'>';
			echo '<input type = "hidden" id="topic_comments_'.$id.$id_comment.'" name="id_topic'.$topic_id.'" value='.$topic_id.'>';
			echo '</div>';
			echo '<div id="form_comments_' . $id.$id_comment . '" style="width:500px"></div>';
			
			
			if (isset($item['children'])) {                    
				showTree2($item['children'], $level + 1, $topic_id );
			} 
        }
}

foreach ($topics as $topic) {
    ?>
    <section class="bg-warning">
		<!-- <form class="navbar-form" role="search" > -->
		
        <div class="row">
            <div class="col-xs-12">
                <h3><?=$topic['title'];?></h3>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-8">
                <p class="text-muted">
                    <?=nl2br($topic['description']);?>
                </p>
            </div>
            <div class="col-xs-4">
			
				<?php include('votes_form.phtml')?>
			
            </div>
        </div>

		<!---   add comments  --->
		<div>
			<button type="button" id="form_<?php echo $topic['id']; ?>" class="btn btn-default btn-s"><span class="glyphicon glyphicon-comment" class="show_hide"></span> Add comment</button>
			</br></br>

			<div id="comment_form_<?php echo $topic['id']; ?>" style="width:500px;">
			</div>

		</div>	
		<!---   add comments  --->
		
		

		<!---   show comments  --->
		
		<?php if(count($topic['comments']) != 0) { ?>
		
			<fieldset class="alert alert-success" style="width:800px" >
			<legend style="margin-bottom:10px; font-size:16px;">Comments</legend>

			<?php $results = showTree2($topic['comments'], $level =0, $topic['id']); ?>

			</fieldset>
			
		
		<?php } ?>

		<!---   show comments  --->		


    </section>
    <hr>
	
    <?php } ?>

<form class="navbar-form navbar-right" role="search">
	<a href="/about" class="btn btn-default"><span class="glyphicon glyphicon-info-sign"></span> About</a>
</form>


<!---  comments --->


<script type="text/javascript">
$("[id^='form_']").on("click", function() {
	createForm(this.id, "comment_"+this.id, (this.id).substr(5), 0);
});
$("[id^='comments_']").on("click", function() {

	createForm(this.id, "form_"+this.id, document.getElementById('topic_'+this.id).value, document.getElementById('topic_'+this.id).value );
});
</script>



<script type="text/javascript">

	function createForm(id, nume, value_id, value) {

	
	if ($("#myForm_"+id).length === 0){

		my_form=document.createElement('FORM');
		my_form.setAttribute("name","myForm_"+id);
		my_form.setAttribute("id","myForm_"+id);
		my_form.setAttribute("method","POST");
		my_form.setAttribute("action","/addCommenttoDB");

		my_tb=document.createElement('INPUT');
		my_tb.setAttribute("class", "form-control");
		my_tb.setAttribute("width", "200px");
		my_tb.setAttribute("type", "TEXT");
		my_tb.setAttribute("name", "name");

		my_tb_label = document.createElement('label'); // Create Label for Name Field
		my_tb_label.setAttribute("class","col-sm-2 control-label");
		my_tb_label.innerHTML = 'Name: ';

		my_form.appendChild(my_tb_label);
		my_form.appendChild(my_tb);

		linebreak = document.createElement('br');
		my_form.appendChild(linebreak);

		my_tb_label2 = document.createElement('label'); // Create Label for Name Field
		my_tb_label2.setAttribute("class","col-sm-2 control-label");
		my_tb_label2.innerHTML = 'Comment: ';
		
		my_tb2=document.createElement('textarea');;
		my_tb2.setAttribute("name", "comment");
		my_tb2.setAttribute("rows", "3");
		my_tb2.setAttribute("cols", "60");

		my_form.appendChild(my_tb_label2);
		my_form.appendChild(my_tb2);

		my_tb3=document.createElement('INPUT');
		my_tb3.setAttribute("type", "hidden");
		my_tb3.setAttribute("name", "id_parrent");
		my_tb3.setAttribute("value", value);

		my_tb4=document.createElement('INPUT');
		my_tb4.setAttribute("type", "hidden");
		my_tb4.setAttribute("name", "id_comment");
		my_tb4.setAttribute("value", value);

		my_tb5=document.createElement('INPUT');
		my_tb5.setAttribute("type", "hidden");
		my_tb5.setAttribute("name", "id_topic");
		my_tb5.setAttribute("value", value_id);
		
		my_form.appendChild(my_tb3);
		my_form.appendChild(my_tb4);
		my_form.appendChild(my_tb5);
		
		submitelement = document.createElement('input'); // Append Submit Button
		submitelement.setAttribute("type", "submit");
		submitelement.setAttribute("name", "submit");
		submitelement.setAttribute("value", "Send");
		submitelement.setAttribute("class", "btn btn-default btn-s");
		my_form.appendChild(submitelement);

		document.getElementById(nume).appendChild(my_form);
		$("#"+nume).show();

	} else {
		$("#"+nume).slideToggle();
	};

	
};

</script>

	