
				<form class="navbar-form" role="search" >
                <p class="pull-right">
				<a href="/vote/add?id=<?=$topic['id']; ?>" class="btn btn-success"><span class="glyphicon glyphicon-thumbs-up">
				<strong><?=(isset($topic['count'])) ? $topic['count'] : 0;?></strong>
				</span>
				</a>
				<a href="/vote/minus?id=<?=$topic['id']; ?>" class="btn btn-danger"><span class="glyphicon glyphicon-thumbs-down">
				<strong><?=(isset($topic['down'])) ? $topic['down'] : 0;?></strong>
				</span>
				</a>
                    <a href="/edit?id=<?=$topic['id']; ?>" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                    <a href="/delete?id=<?=$topic['id']; ?>" class="btn btn-danger" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="top" data-title="Are you sure?" data-content=" This cannot be undone!" onclick="return confirm('Are you sure?')">
					<span class="glyphicon glyphicon-remove"></span> Delete</a>

                </p>
				</form>